server:
  port: 9090

spring:
  application:
    name: auth-service

  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:auth-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
